// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init(arg1) {
  return window['go']['backend']['Server']['Init'](arg1);
}

export function SetSetting(arg1) {
  return window['go']['backend']['Server']['SetSetting'](arg1);
}

export function Start() {
  return window['go']['backend']['Server']['Start']();
}
