// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {backend} from '../models';

export function Init(arg1:context.Context):Promise<void>;

export function SetAccountState(arg1:backend.AccountState):Promise<void>;

export function Start():Promise<void>;
