// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadProcess(arg1:string,arg2:any):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;
